<?php
/**
 * Implementation of hook_menu().
 */

function civicrm_demo_menu(){
  return array(
    'admin/config/civicrm_demo' => array(
      'title'            => 'Generate demo data of CiviCRM',
      'access arguments' => array('administer neticrm'),
      'page callback'    => 'drupal_get_form',
      'page arguments'    => array('civicrm_demo_settings'),
      'file' => 'civicrm_demo.admin.inc'
    )
  );
}
