<?php

/**
 * Implementation of hook_install()
 */
function civicrm_demo_install() {
  include_once "civicrm_demo.module";
  include_once "civicrm_demo.utils.inc";
  civicrm_initialize();
  
  if(variable_get('civicrm_demo_sample_data', 0)) {
    $vars['limit'] = 20;
    civicrm_demo_process_contact($vars);

    $vars['limit'] = 5;
    civicrm_demo_process_event($vars);

    $vars['limit'] = 50;
    civicrm_demo_process_contribution($vars);
    civicrm_demo_create_custom_profile();

    $vars['limit'] = 3;
    civicrm_demo_process_membership($vars);
  }
  else{
    $have_event = CRM_Core_DAO::singleValueQuery("SELECT count(*) FROM civicrm_event");
    if (!$have_event) {
      $vars['limit'] = 5;
      civicrm_demo_process_event($vars);
    }

    $have_page = CRM_Core_DAO::singleValueQuery("SELECT count(*) FROM civicrm_contribution_page");
    if (!$have_page) {
      $vars['limit'] = 1;
      civicrm_demo_process_contribution($vars);
    }

    $have_custom_field = CRM_Core_DAO::singleValueQuery("SELECT id FROM civicrm_custom_group WHERE name = 'shou_ju_zi_xun'");
    if (!$have_custom_field) {
      civicrm_demo_create_custom_profile();
    }
  }

  if(variable_get('civicrm_demo_sample_data_ci', 0)) {
    // add report ofr TaiwanTax
    $title = '臺灣財政部所得扣除額';
    $desc = '提供給財政部所得扣除額的報表';
    $url = 'contribute/taiwantax';
    $class= 'CRM_Report_Form_Contribute_TaiwanTax';
    $components = CRM_Core_Component::getComponents();
    $result = civicrm_demo_add_report($title, $desc, $url, $class, $components['CiviContribute']->componentID);
  }
}
