<?php

const CIVICRM_JVALIDATE_LIBRARY = 'civicrm-js-jvalidate';

function civicrm_jvalidate_page_attachments(array &$page) {
  $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $config = array('jvalidate' => array(
    'ext'=> t('Phone Ext.'),
    'extprompt' => t('Enter phone number Ext.'),
    'notw' => t('other format?'),
    'notwprompt' => t('Enter id below.'),
    'imeNotify' => t('Please close your Input Method to input number'),
    'lang' => $lang,
    'phoneMask' => '',
    'mobileMask' => '',
    'phoneValidator' => '',
  ));
  $phone_mask = \Drupal::config('civicrm_jvalidate.settings')->get('phone_mask');
  $mobile_mask = \Drupal::config('civicrm_jvalidate.settings')->get('mobile_mask');
  $phone_validator = \Drupal::config('civicrm_jvalidate.settings')->get('phone_validator');
  if ($phone_mask) {
    $config['jvalidate']['phoneMask'] = $phone_mask;
  }
  if ($mobile_mask) {
    $config['jvalidate']['mobileMask'] = $mobile_mask;
  }
  if ($phone_validator) {
    $config['jvalidate']['phoneValidator'] = $phone_validator;
  }
  $page['#attached']['drupalSettings'] += $config;
}

function civicrm_jvalidate_library_info_alter(&$libraries, $extension) {
  // this will add js library into library, and use cj to trigger that
  if ($extension == 'civicrm') {
    $min = \Drupal::config('system.performance')->get('js.preprocess') ? '.min' : '';
    $libraries[CIVICRM_JVALIDATE_LIBRARY] = [
      'weight' => -5,
      'header' => true,
      'dependencies' => [
        'civicrm/civicrm-js-packages',
      ],
    ];

    $jvalidate = ['weight' => -5, 'minified' => true];
    $libraries[CIVICRM_JVALIDATE_LIBRARY]['js']['../neticrm/civicrm_jvalidate/js/jquery.validate'.$min.'.js'] = $jvalidate;

    // TODO: we will have issue here. hook_library_info_alter only triggered once
    $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
    if ($lang == 'zh-hant') {
      $libraries[CIVICRM_JVALIDATE_LIBRARY]['js']['../neticrm/civicrm_jvalidate/js/localization/messages_tw.js'] = $jvalidate;
    }
    $libraries[CIVICRM_JVALIDATE_LIBRARY]['js']['../neticrm/civicrm_jvalidate/js/custom-methods.js'] = $jvalidate;
    $libraries[CIVICRM_JVALIDATE_LIBRARY]['js']['../neticrm/civicrm_jvalidate/js/jquery.maskedinput.js'] = $jvalidate;
    $libraries[CIVICRM_JVALIDATE_LIBRARY]['js']['../neticrm/civicrm_jvalidate/js/custom-masks.js'] = $jvalidate;
    $libraries[CIVICRM_JVALIDATE_LIBRARY]['js']['../neticrm/civicrm_jvalidate/civicrm_jvalidate.js'] = $jvalidate;
  }
}

/**
 * Implementation of hook_civicrm_buildForm().
 */
function civicrm_jvalidate_civicrm_buildForm($formName, &$form) {
  static $add;

  $form_name = $form->_attributes['name'];
  if($form_name == 'Dynamic'){
    $is_dynamic = true;
  }

  if($_GET['q'] != 'civicrm/event/register' && $_GET['q'] != 'civicrm/profile/create' && $_GET['q']!= 'civicrm/contribute/transact' && $_GET['q'] != 'civicrm/contact/add' && $_GET['q'] != 'civicrm/profile/edit' && empty($is_dynamic)){
    return;
  }

  if(isset($_GET['_qf_Confirm_display']) || isset($_GET['_qf_ThankYou_display'])){
    return;
  }

  if(!$add){
    // libraries already added, add logic here
    $params['library'] = 'civicrm/'.CIVICRM_JVALIDATE_LIBRARY;
    CRM_Utils_System::addJs($params, '');
    $add = TRUE;
  }
}