<?php
/**
 * Implementation of hook_civicrm_buildForm().
 */
function civicrm_jvalidate_civicrm_buildForm($formName, &$form) {
  static $add;

  if($_GET['q'] != 'civicrm/event/register' && $_GET['q'] != 'civicrm/profile/create' && $_GET['q']!= 'civicrm/contribute/transact' && $_GET['q'] != 'civicrm/contact/add'){
    return;
  }

  if(isset($_GET['_qf_Confirm_display']) || isset($_GET['_qf_ThankYou_display'])){
    return;
  }

  if(!$add){
    $js = '';
    $path = drupal_get_path('module', 'civicrm_jvalidate');
    $t = array('jvalidate' => array(
      'ext'=> t('Phone Ext.'),
      'extprompt' => t('Enter phone number Ext.'),
      'notw' => t('other format?'),
      'notwprompt' => t('Enter id below.'),
    ));
    $options = array(
      'type' => 'file', 
      'scope' => 'footer',
    );
    drupal_add_js($t, 'setting');
    drupal_add_js($path.'/js/jquery.validate.min.js', $options);
    drupal_add_js($path.'/js/localization/messages_tw.js', $options);
    drupal_add_js($path.'/js/custom-methods.js', $options);
    drupal_add_js($path.'/js/jquery.maskedinput.js', $options);
    drupal_add_js($path.'/civicrm_jvalidate.js', $options);
    $add = TRUE;
  }
}
