<?php
/**
 * Implementation of hook_civicrm_buildForm().
 */
function civicrm_jvalidate_civicrm_buildForm($formName, &$form) {
  static $add;

  if($_GET['q'] != 'civicrm/event/register' && $_GET['q'] != 'civicrm/profile/create' && $_GET['q']!= 'civicrm/contribute/transact' && $_GET['q'] != 'civicrm/contact/add' && $_GET['q'] != 'civicrm/profile/edit'){
    return;
  }

  if(isset($_GET['_qf_Confirm_display']) || isset($_GET['_qf_ThankYou_display'])){
    return;
  }

  if(!$add){
    global $language;
    $js = '';
    $path = drupal_get_path('module', 'civicrm_jvalidate');
    $config = array('jvalidate' => array(
      'ext'=> t('Phone Ext.'),
      'extprompt' => t('Enter phone number Ext.'),
      'notw' => t('other format?'),
      'notwprompt' => t('Enter id below.'),
      'imeNotify' => t('Please close your Input Method to input number'),
      'lang' => $language->language,
      'phoneMask' => '',
      'mobileMask' => '',
      'phoneValidator' => '',
    ));
    $phone_mask = variable_get('civicrm_jvalidate_phone_mask', '');
    $mobile_mask = variable_get('civicrm_jvalidate_mobile_mask', '');
    $phone_validator = variable_get('civicrm_jvalidate_phone_validator', '');
    if ($phone_mask) {
      $config['jvalidate']['phoneMask'] = $phone_mask;
    }
    if ($mobile_mask) {
      $config['jvalidate']['mobileMask'] = $mobile_mask;
    }
    if ($phone_validator) {
      $config['jvalidate']['phoneValidator'] = $phone_validator;
    }
    $options = array(
      'type' => 'file',
    );
    drupal_add_js($config, 'setting');
    $min = variable_get('jquery_update_compression_type', 'min') == 'none' ? '' : '.min';
    drupal_add_js($path."/js/jquery.validate$min.js", $options);
    if($config['jvalidate']['lang'] == "zh-hant"){
      drupal_add_js($path.'/js/localization/messages_tw.js', $options);
    }
    drupal_add_js($path.'/js/custom-methods.js', $options);
    drupal_add_js($path.'/js/jquery.maskedinput.js', $options);
    drupal_add_js($path.'/civicrm_jvalidate.js', $options);
    $add = TRUE;
  }
}
