<?php
// $Id: devel.install,v 1.24.2.7 2009/07/30 19:38:48 weitzman Exp $
/**
 * @file
 *   Install file for civicrm_nccc module.
 */

/**
 * Implementation of hook_schema()
 */
function civicrm_nccc_schema() {
  $schema['civicrm_contribution_nccc'] = [
    'fields' => [
      'cid' => [
        'description' => 'Contribution id for civicrm',
        'type' => 'int',
        'length' => '11',
        'not null' => TRUE,
      ],
      'created' => [
        'description' => 'Submit time for user confirmed transaction.',
        'type' => 'int',
        'length' => '11',
        'not null' => FALSE,
      ],
      'pan' => [
        'description' => 'Masked card number',
        'type' => 'varchar',
        'length' => '19',
        'not null' => FALSE,
      ],
      'transcode' => [
        'description' => 'Transaction code',
        'type' => 'varchar',
        'length' => '6',
        'not null' => FALSE,
      ],
      'transmode' => [
        'description' => 'Transaction mode',
        'type' => 'int',
        'size' => 'tiny',
        'not null' => FALSE,
      ],
      'transdatetime' => [
        'description' => 'Transaction date time',
        'type' => 'datetime',
        'not null' => FALSE,
      ],
      'approvecode' => [
        'description' => 'Transaction approve code',
        'type' => 'varchar',
        'length' => '16',
        'not null' => FALSE,
      ],
      'responsecode' => [
        'description' => '',
        'type' => 'varchar',
        'length' => '3',
        'not null' => FALSE,
      ],
      'responsemsg' => [
        'description' => 'Response message of transaction',
        'type' => 'varchar',
        'length' => '128',
        'not null' => FALSE,
      ],
      'installtype' => [
        'description' => 'Installment type',
        'type' => 'varchar',
        'length' => '1',
        'not null' => FALSE,
      ],
      'install' => [
        'description' => 'Installment number',
        'type' => 'int',
        'length' => '11',
        'not null' => FALSE,
      ],
      'firstamt' => [
        'description' => 'First installment amount',
        'type' => 'int',
        'length' => '11',
        'not null' => FALSE,
      ],
      'eachamt' => [
        'description' => 'Each installment amount',
        'type' => 'int',
        'length' => '11',
        'not null' => FALSE,
      ],
      'fee' => [
        'description' => 'Fee of transaction',
        'type' => 'int',
        'length' => '11',
        'not null' => FALSE,
      ],
      'redeem' => [
        'description' => 'Redeem data container. Include RedeemType, RedeemUsed, RedeemBalance, CreditAmt',
        'type' => 'text',
        'not null' => FALSE,
      ],
      'riskmark' => [
        'description' => 'High risk card number',
        'type' => 'varchar',
        'length' => '8',
        'not null' => FALSE,
      ],
      'foreigncard' => [
        'description' => 'Card from forign, support VISA Master JSB. Y/N or NULL',
        'type' => 'varchar',
        'length' => '8',
        'not null' => FALSE,
      ],
      'secure_status' => [
        'description' => '3D verify result, Y/N or NULL',
        'type' => 'varchar',
        'length' => '8',
        'not null' => FALSE,
      ],
    ],
    'primary key' => ['cid'],
    'mysql_suffix' => 'ENGINE = InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci',
  ];
  return $schema;
}

/**
 * Implementation of hook_install()
 */
function civicrm_nccc_install() {
  drupal_install_schema('civicrm_nccc');
  civicrm_initialize();
  require_once "CRM/Core/DAO.php";
  require_once('CRM/Core/OptionValue.php');
  require_once('CRM/Core/Action.php');

  // new payment processor
  $sql = "INSERT INTO civicrm_payment_processor_type 
  (name, title, description, is_active, is_default, user_name_label, password_label, signature_label, subject_label, class_name, url_site_default, url_api_default, url_recur_default, url_button_default, url_site_test_default, url_api_test_default, url_recur_test_default, url_button_test_default, billing_mode, is_recur, payment_type)
  VALUES 
  ('NCCC', '聯合信用卡', NULL, 1, 0, '特店代號（MerchantID）', '端末機代號（TerminalID）', '交易編號開頭文字', '', 'Payment_NCCC', 'https://nccnet-ec.nccc.com.tw/merchant/HPPRequest', NULL, NULL, NULL, 'https://nccnet-ectest.nccc.com.tw/merchant/HPPRequest', NULL, NULL, NULL, 4, 0, 1)";

  CRM_Core_DAO::executeQuery($sql);
  $ppt_id = CRM_Core_DAO::singleValueQuery("SELECT id FROM civicrm_payment_processor_type WHERE name LIKE 'NCCC'");

}

/**
 * Implementation of hook_uninstall().
 */
function civicrm_nccc_uninstall() {
  civicrm_initialize();
  require_once "CRM/Core/DAO.php";
  CRM_Core_DAO::executeQuery("DELETE FROM civicrm_payment_processor_type WHERE name LIKE 'NCCC'");
  CRM_Core_DAO::executeQuery("DELETE FROM civicrm_payment_processor WHERE payment_processor_type LIKE 'NCCC'");
  CRM_Core_DAO::executeQuery("OPTIMIZE TABLE civicrm_payment_processor_type");

  // we won't delete instrument for preserve contribution record
  // delete schema from drupal
  drupal_uninstall_schema('civicrm_nccc');
}

/**
 * Implementation of hook_enable().
 */
function civicrm_nccc_enable() {
  civicrm_initialize();
  require_once "CRM/Core/DAO.php";
  CRM_Core_DAO::executeQuery("UPDATE civicrm_payment_processor_type SET is_active = 1 WHERE name LIKE 'NCCC'");
  CRM_Core_DAO::executeQuery("UPDATE civicrm_payment_processor SET is_active = 1 WHERE payment_processor_type LIKE 'NCCC'");
}

/**
 * Implementation of hook_disable().
 */
function civicrm_nccc_disable() {
  civicrm_initialize();
  require_once "CRM/Core/DAO.php";
  CRM_Core_DAO::executeQuery("UPDATE civicrm_payment_processor_type SET is_active = 0 WHERE name LIKE 'NCCC'");
  CRM_Core_DAO::executeQuery("UPDATE civicrm_payment_processor SET is_active = 0 WHERE payment_processor_type LIKE 'NCCC'");
}
