<?php

/**
 * hook_civicrm_tokens
 */
function civicrm_annual_receipt_civicrm_tokens(&$tokens){
  $tokens['receipt'] = array(
    'receipt.thisyear' => ts('Receipt info in this year'),
    'receipt.lastyear' => ts('Receipt info in last year'),
    'receipt.all' => ts('Receipt info in all lifetime'),
  );
}

/**
 * hook_civicrm_tokenvalues
 */
function civicrm_annual_receipt_civicrm_tokenValues(&$values, $cids, $job = NULL, $tokens = array(), $context = NULL){
  if(!empty($tokens['receipt'])){
    $year = date('Y');
    $header = NULL;
    $header = array(
      ts('Receipt ID'),
      ts('Contribution Types'),
      ts('Payment Instrument'),
      ts('Receipt Date'),
      ts('Total Amount'),
    );
    $attr = array(
      'cellpadding' => 5,
      'cellspacing' => 0,
      'border' => 1,
      'style' => 'font-size: 13px;',
    );
    $table = array(
      'header' => $header,
      'rows' => array(),
      'attributes' => $attr,
    );
    foreach($cids as $k => $cid){
      // TODO: theme table need to be modify for d7
      $records = array();
      if(!empty($tokens['receipt']['thisyear'])){
        $option = array('year' => $year);
        $records['receipt.thisyear'] = CRM_Contribute_BAO_Contribution::getAnnualReceiptRecord($cid, $option);
      }
      if(!empty($tokens['receipt']['lastyear'])){
        $option = array('year' => $year - 1);
        $records['receipt.lastyear'] = CRM_Contribute_BAO_Contribution::getAnnualReceiptRecord($cid, $option);
      }
      if(!empty($tokens['receipt']['all'])){
        $records['receipt.all'] = CRM_Contribute_BAO_Contribution::getAnnualReceiptRecord($cid);
      }
      foreach($records as $type => $row) {
        $table['rows'] = array();
        foreach($row as $key => $col) {
          if (!empty($col)) {
            $table['rows'][] = array(
              $col['receipt_id'],
              $col['contribution_type'],
              $col['instrument'],
              $col['receipt_date'],
              $col['total_amount'],
            );
          }
        }
        if(!empty($table['rows'])){
          $values[$cid][$type] = theme('table', $table);
        }
      }
    }
  }
}


/**
 * hook_civicrm_searchTasks
 */
function civicrm_annual_receipt_civicrm_searchTasks($objectType, &$tasks) {
  if($objectType == 'contact'){
    if (CRM_Core_Permission::access('CiviContribute')) {
      $tasks[] = array(
        'title' => ts('Print Annual Receipt'),
        'class' => 'CRM_Contact_Form_Task_AnnualReceipt',
        'result' => TRUE,
      );
    }
  }
}
