<?php
function civicrm_statistics_cron(){
  module_load_include('inc', 'civicrm_statistics', 'civicrm_statistics.stat');
  if($_SERVER['REQUEST_TIME'] - variable_get('civicrm_statistics_run', 0) > 80000){
    civicrm_statistics_fetch();
  }

  $year = (int)date('Y');
  if ($_SERVER['REQUEST_TIME'] >= strtotime("$year-01-10") && $_SERVER['REQUEST_TIME'] <= strtotime("$year-01-31")) {
    $base_year = $year - 1;
    $exists = variable_get('civicrm_statistics_run_annual', array());
    if (empty($exists[$base_year]) && date('G') >= 3 && date('G') <= 7) {
      sleep(mt_rand(1, 60)); // multiple sites will fetch at the same time, delay awhile for each site
      civicrm_statistics_annual_fetch($base_year);
      $exists[$base_year] = $_SERVER['REQUEST_TIME'];
      variable_set('civicrm_statistics_run_annual', $exists);
    }
  }
}
