<?php
/**
 * Implements hook_install().
 */
function civicrm_alter_translation_install() {
  civicrm_initialize();
  $params = array(
    'customTranslateFunction' => 'civicrm_alter_translation',
  );
  CRM_Core_BAO_ConfigSetting::add($params);
}

/**
 * Implements hook_disable().
 */
function civicrm_alter_translation_uninstall() {
  civicrm_initialize();
  $params = array(
    'customTranslateFunction' => '',
  );
  CRM_Core_BAO_ConfigSetting::add($params);
}
