<?php

/**
 * hook_civicrm_tokens
 */
function civicrm_year_receipt_civicrm_tokens(&$tokens){
  $tokens['receipt'] = array(
    'receipt.lastyear' => ts('Receipt info in last year'),
    'receipt.all' => ts('Receipt info in all lifetime'),
  );
}

/**
 * hook_civicrm_tokenvalues
 */
function civicrm_year_receipt_civicrm_tokenValues(&$values, $cids, $job = null){
  $year = date('Y');
  $year--;
  $header = NULL;
  if(function_exists('ts')){
    $header = array(
      ts('Receipt ID'),
      ts('Contribution Types'),
      ts('Payment Instrument'),
      ts('Receipt Date'),
      ts('Total Amount'),
    );
  }
  $attr = array(
    'cellpadding' => 5,
    'cellspacing' => 0,
    'border' => 0,
    'style' => 'font-size: 13px;',
  );
  foreach($cids as $k => $cid){
    // TODO: theme table need to be modify for d7
    $record_lastyear = CRM_Contribute_BAO_Contribution::getReceiptYearlyRecord($cid, $year);
    if($record_lastyear){
      $values[$cid]['receipt.lastyear'] = theme('table', $header, $record_lastyear, $attr);
    }
    $record_all = CRM_Contribute_BAO_Contribution::getReceiptYearlyRecord($cid);
    if($record_all){
      $values[$cid]['receipt.all'] = theme('table', $header, $record_all, $attr);
    }
  }
}

