<?php

/**
 * hook_civicrm_tokens
 */
function civicrm_year_receipt_civicrm_tokens(&$tokens){
  $tokens['receipt'] = array(
    'receipt.lastyear' => ts('Receipt info in last year'),
    'receipt.all' => ts('Receipt info in all lifetime'),
  );
}

/**
 * hook_civicrm_tokenvalues
 */
function civicrm_year_receipt_civicrm_tokenValues(&$values, $cids, $job = null){
  $year = date('Y');
  $year--;
  $header = NULL;
  if(function_exists('ts')){
    $header = array(
      ts('Transaction ID'),
      ts('Receipt ID'),
      ts('Receipt Date'),
      ts('Receive Date'),
      ts('Total Amount'),
    );
  }
  $attr = array(
    'cellpadding' => 5,
    'cellspacing' => 0,
    'border' => 0,
    'style' => 'font-size: 13px;',
  );
  foreach($cids as $k => $cid){
    // TODO: theme table need to be modify for d7
    $record_lastyear = civicrm_year_receipt_record($cid, $year);
    if($record_lastyear){
      $values[$cid]['receipt.lastyear'] = theme('table', $header, $record_lastyear, $attr);
    }
    $record_all = civicrm_year_receipt_record($cid);
    if($record_all){
      $values[$cid]['receipt.all'] = theme('table', $header, $record_all, $attr);
    }
  }
}

function civicrm_year_receipt_record($contact_id, $year = 'all'){
  if($year == 'all'){
    $where = '';
  }
  else{
    $start = $year.'-01-01 00:00:00';
    $end = $year.'-12-31 23:59:59';
    $where = "AND c.receipt_date >= '$start' AND c.receipt_date <= '$end'";
  }
  $args = array(
    1 => array($contact_id, 'Integer'),
  );
  $query = CRM_Core_DAO::executeQuery("SELECT c.id, c.trxn_id, c.receipt_id, DATE(c.receipt_date) as receipt_date, DATE(c.receive_date) as receive_date, c.total_amount FROM civicrm_contribution c WHERE c.contact_id = %1 AND c.is_test = 0 AND c.contribution_status_id = 1 $where ORDER BY c.receipt_date ASC", $args);

  $record = array();
  while($query->fetch()){
    $record[] = array(
      $query->trxn_id,
      $query->receipt_id,
      $query->receipt_date,
      $query->receive_date,
      $query->total_amount,
    );
  }
  return $record;
}

