<?php

/**
 * Implementation of hook_init()
 */
function civicrm_ebill_ba_init(){
  if(strstr($_GET['q'], 'ebill')){
    $GLOBALS['conf']['cache'] = FALSE;
  }
}

/**
 * Implementation of hook_menu()
 */
function civicrm_ebill_ba_menu(){
  return array(
    'ebill/ipn' => array(
      'access callback' => true,
      'page callback' => 'civicrm_ebill_ba_ipn',
      'type' => MENU_CALLBACK,
      'weight' => 0,
      'file' => 'civicrm_ebill_ba.ipn.inc',
    ),
  );
}

/**
 * Implementation of hook_civicrm_buildForm()
 */
function civicrm_ebill_ba_civicrm_buildForm($form_name, &$form){
  switch($form_name){
    case 'CRM_Contribute_Form_Contribution_Main':
    case 'CRM_Event_Form_Registration_Register':
      if(!empty($_SESSION['ebill_ba']['submitted'])){
        $submitted = $_SESSION['ebill_ba']['submitted'];
        unset($_SESSION['ebill_ba']);
        drupal_set_message(t("You just submit a payment. You may want to check your email to follow payment instruction, or try submit this form again."), 'error');
      }
      else{
        $submitted = FALSE;
      }
      break;
    case 'CRM_Contribute_Form_Contribution_ThankYou':
    case 'CRM_Event_Form_Registration_ThankYou':
      unset($_SESSION['ebill_ba']);
      break;
  }
}

function _civicrm_ebill_ba_trxn_id($id, $is_test){
  $trxn_id = $id;

  // prepare for hook
  $data = array(
    'module' => 'civicrm_ebill_ba',
    'is_test' => $is_test,
    'trxn_id' => $trxn_id,
    'id' => $id,
  );
  drupal_alter('civicrm_trxn_id', $data);

  if(strlen($data['trxn_id']) > 16){
    watchdog('civcirm_ebill_ba', 'Error when generate trxn_id');
    return FALSE;
  }
  return $data['trxn_id'];
}

