<?php

/**
 * Implementation of hook_civicrm_buildForm()
 */
function civicrm_ebill_ba_civicrm_buildForm($form_name, &$form){
  switch($form_name){
    case 'CRM_Contribute_Form_Contribution_Main':
    case 'CRM_Event_Form_Registration_Register':
      if(!empty($_SESSION['ebill_ba']['submitted'])){
        $submitted = $_SESSION['ebill_ba']['submitted'];
        unset($_SESSION['ebill_ba']);
        drupal_set_message(t("You just submit a payment. You may want to check your email to follow payment instruction, or try submit this form again."), 'error');
      }
      else{
        $submitted = FALSE;
      }
      break;
    case 'CRM_Contribute_Form_Contribution_ThankYou':
    case 'CRM_Event_Form_Registration_ThankYou':
      unset($_SESSION['ebill_ba']);
      break;
  }
}

function _civicrm_ebill_ba_trxn_id($is_test, $id){
  $prefix = date('Ymd');
  if($is_test){
    $prefix = '9'.$prefix;
    $suffix = sprintf("%07d", $id);
  }
  else{
    $suffix = sprintf("%08d", $id);
  }
  return $prefix.$suffix; 
}

