<?php

namespace Drupal\neticrm_drush;

/**
 * Helpers for the message template deployment check.
 */
class MessageTemplateScanner {

  const FIELDS = ['msg_subject', 'msg_text', 'msg_html'];

  /**
   * Find workflow defaults changed from or missing their reserved copy.
   */
  public static function customTemplates(array $templates): array {
    $reserved = [];
    foreach ($templates as $template) {
      if (!empty($template['is_reserved'])) {
        $reserved[$template['workflow_id']] = $template;
      }
    }

    $custom = [];
    foreach ($templates as $template) {
      // Newsletter and ordinary user templates do not use Smarty rendering.
      if (!empty($template['is_reserved']) || empty($template['workflow_id']) || empty($template['is_default'])) {
        continue;
      }
      $workflow = $template['workflow_id'];
      if (!isset($reserved[$workflow])) {
        $custom[] = $template;
      }
      else {
        foreach (self::FIELDS as $field) {
          if ((string) $template[$field] !== (string) $reserved[$workflow][$field]) {
            $custom[] = $template;
            break;
          }
        }
      }
    }
    return $custom;
  }

  /**
   * Enable strict rendering in the site settings without executing the file.
   */
  public static function enable(string $settingsPath): void {
    $path = realpath($settingsPath);
    if ($path === FALSE || !is_file($path) || !is_readable($path) || !is_writable($path) || !is_writable(dirname($path))) {
      throw new \RuntimeException('The CiviCRM settings file and its directory must be writable.');
    }
    $original = file_get_contents($path);
    if ($original === FALSE) {
      throw new \RuntimeException('Unable to read the CiviCRM settings file.');
    }

    // Keep offsets while excluding comments and quoted examples from the search.
    $tokens = [];
    $offset = 0;
    $depth = 0;
    foreach (token_get_all($original, TOKEN_PARSE) as $token) {
      $id = is_array($token) ? $token[0] : NULL;
      $text = is_array($token) ? $token[1] : $token;
      if (!in_array($id, [T_WHITESPACE, T_COMMENT, T_DOC_COMMENT], TRUE)) {
        $tokens[] = [$id, $text, $offset, $depth];
      }
      if (in_array($text, ['(', '[', '{'], TRUE) || in_array($id, [T_CURLY_OPEN, T_DOLLAR_OPEN_CURLY_BRACES], TRUE)) {
        $depth++;
      }
      elseif (in_array($text, [')', ']', '}'], TRUE)) {
        $depth--;
      }
      $offset += strlen($text);
    }
    $setting = 'CIVICRM_SECURE_MESSAGE_TEMPLATES';
    $legacy = 'CIVICRM_UNTRUSTED_MESSAGE_TEMPLATES';
    $anchor = 'CIVICRM_TEMPLATE_COMPILEDIR';
    $definitions = [];
    $constantDeclaration = FALSE;
    foreach ($tokens as $index => $token) {
      if ($token[0] === T_CONST) {
        $constantDeclaration = TRUE;
      }
      elseif ($token[1] === ';') {
        $constantDeclaration = FALSE;
      }
      if ($constantDeclaration && $token[0] === T_STRING && in_array($token[1], [$setting, $legacy, $anchor], TRUE)) {
        throw new \RuntimeException('Cannot move a const declaration; use a standalone define() for the setting.');
      }
      if (strtolower(ltrim($token[1], '\\')) !== 'define' ||
        ($tokens[$index + 1][1] ?? NULL) !== '(' ||
        ($tokens[$index + 2][0] ?? NULL) !== T_CONSTANT_ENCAPSED_STRING
      ) {
        continue;
      }
      $name = substr($tokens[$index + 2][1], 1, -1);
      if (!in_array($name, [$setting, $legacy, $anchor], TRUE)) {
        continue;
      }
      // Moving a conditional or embedded definition could change its meaning.
      $previous = $tokens[$index - 1] ?? [NULL, ''];
      if (($tokens[$index + 3][1] ?? NULL) !== ',' || $token[3] !== 0 || ($previous[0] !== T_OPEN_TAG && !in_array($previous[1], [';', '}'], TRUE)) || isset($definitions[$name])) {
        throw new \RuntimeException('Settings must have one unconditional, standalone definition per constant.');
      }
      $end = $index + 4;
      while (isset($tokens[$end]) && !($tokens[$end][1] === ')' && $tokens[$end][3] === 1)) {
        $end++;
      }
      if (($tokens[$end + 1][1] ?? NULL) !== ';' ||
        ($name !== $anchor && ($end !== $index + 5 || !preg_match('/^(TRUE|FALSE|0|1)$/i', $tokens[$index + 4][1])))
      ) {
        throw new \RuntimeException('Cannot safely update the message template setting; use a standalone literal TRUE or FALSE definition.');
      }
      $definitions[$name] = [$token[2], $tokens[$end + 1][2] + 1];
    }
    if (!isset($definitions[$anchor])) {
      throw new \RuntimeException('Cannot locate a single standalone CIVICRM_TEMPLATE_COMPILEDIR definition.');
    }

    // Remove old placements, including comments generated by this command or installer.
    $edits = [];
    foreach ([$setting, $legacy] as $name) {
      if (!isset($definitions[$name])) {
        continue;
      }
      [$start, $end] = $definitions[$name];
      $lineStart = strrpos(substr($original, 0, $start), "\n");
      $lineStart = $lineStart === FALSE ? 0 : $lineStart + 1;
      if (trim(substr($original, $lineStart, $start - $lineStart)) === '' && preg_match('/^[ \t]*(?:\r?\n|$)/', substr($original, $end), $match)) {
        $start = $lineStart;
        $end += strlen($match[0]);
        if (preg_match('/^[ \t]*\/\/ (?:Custom message templates passed the (?:strict|secure) Smarty deployment scan\.|New sites use secure message templates; existing sites enable this after scanning\.)\r?\n[ \t]*\z/m', substr($original, 0, $start), $comment, PREG_OFFSET_CAPTURE)) {
          $start = $comment[0][1];
        }
      }
      $edits[] = [$start, $end];
    }
    $insert = $definitions[$anchor][1];
    // Keep any same-line comment attached to the compiled-template setting.
    preg_match('/^[ \t]*(?:(?:\/\/|#)[^\r\n]*|\/\*[^\r\n]*?\*\/[ \t]*)?/', substr($original, $insert), $trailing);
    $insert += strlen($trailing[0]);
    $updated = $original;
    rsort($edits);
    foreach ($edits as [$start, $end]) {
      $updated = substr_replace($updated, '', $start, $end - $start);
      if ($end <= $insert) {
        $insert -= $end - $start;
      }
    }
    $newline = strpos($original, "\r\n") !== FALSE ? "\r\n" : "\n";
    preg_match('/^\s*/', substr($updated, $insert), $spacing);
    $definition = $newline . $newline . '// Custom message templates passed the secure Smarty deployment scan.' . $newline . "define('$setting', TRUE);" . $newline;
    if ($insert + strlen($spacing[0]) < strlen($updated)) {
      $definition .= $newline;
    }
    $updated = substr_replace($updated, $definition, $insert, strlen($spacing[0]));
    if ($updated === $original) {
      return;
    }
    token_get_all($updated, TOKEN_PARSE);

    // Write beside the original so rename is atomic; keep its access controls.
    $temporary = tempnam(dirname($path), '.civicrm-settings-');
    if ($temporary === FALSE) {
      throw new \RuntimeException('Unable to create a temporary CiviCRM settings file.');
    }
    try {
      $stat = stat($path);
      if (!chmod($temporary, $stat['mode'] & 0777) ||
        (fileowner($temporary) !== $stat['uid'] && !chown($temporary, $stat['uid'])) ||
        (filegroup($temporary) !== $stat['gid'] && !chgrp($temporary, $stat['gid'])) ||
        file_put_contents($temporary, $updated) !== strlen($updated)
      ) {
        throw new \RuntimeException('Unable to prepare the CiviCRM settings update; the original file was kept.');
      }
      if (file_get_contents($path) !== $original || !rename($temporary, $path)) {
        throw new \RuntimeException('Unable to replace the CiviCRM settings file; it may have changed during the scan.');
      }
      if (function_exists('opcache_invalidate')) {
        opcache_invalidate($path, TRUE);
      }
    }
    finally {
      if (file_exists($temporary)) {
        unlink($temporary);
      }
    }
  }

}
