<?php

/**
 * Implementation of hook_civicrm_buildForm()
 */
function civicrm_spgateway_civicrm_buildForm($form_name, &$form){
  switch($form_name){
    case 'CRM_Contribute_Form_Contribution_ThankYou':
    case 'CRM_Event_Form_Registration_ThankYou':
      if(!preg_match("/SPGATEWAY/",$form->_paymentProcessor['payment_processor_type'])){
        return;
      }
      $msg = NULL;
      $status = 2; // Pending
      $params = $return_params = [];
      // MGP 1.2
      if (!empty($form->_submitValues['JSONData'])) {
        $return_params = CRM_Core_Payment_SPGATEWAYAPI::dataDecode($form->_submitValues['JSONData']);
      }
      // for upgrade to MGP 2.3
      if (!empty($form->_submitValues['TradeInfo'])) {
        $return_params_decrypt = CRM_Core_Payment_SPGATEWAYAPI::recurDecrypt($form->_submitValues['TradeInfo'], $form->_paymentProcessor);
        $return_params = CRM_Core_Payment_SPGATEWAYAPI::dataDecode($return_params_decrypt);
      }
      if(!empty($form->_submitValues['Period']) && empty($return_params)){
        $return_params_decrypt = CRM_Core_Payment_SPGATEWAYAPI::recurDecrypt($form->_submitValues['Period'], $form->_paymentProcessor);
        $return_params = CRM_Core_Payment_SPGATEWAYAPI::dataDecode($return_params_decrypt);
      }
      CRM_Core_Error::debug_var('spgateway_frontend_return', $return_params);
      // Credit card have result immediately
      if(isset($form->_submitValues) && ($return_params['PaymentType'] == 'CREDIT' || !empty($return_params['PeriodAmt']))) {
        $params['trxn_id'] = $return_params['MerchantOrderNo'];
        if(array_key_exists('RespondCode', $return_params)){
          if($return_params['RespondCode'] == '00'){ // success
            $status = 1;
          }
          else {
            // Prepare error message.
            if (!empty($return_params['Message'])) {
              $msg = $return_params['Status'].': '.$return_params['Message'];
            }
            else {
              $msg = $return_params['Status'].': '._civicrm_spgateway_error_msg($return_params['Status']);
            }
            $status = 4;
          }
        }
        CRM_Contribute_BAO_Contribution_Utils::paymentResultType($form, $params, $status, $msg);
      }
      // non-direct payment
      else {
        $saved_params = $form->controller->get('params');
        // for upgrade to MGP version 2.3
        if (!empty($form->_submitValues['TradeInfo'])) {
          $return_params_decrypt = CRM_Core_Payment_SPGATEWAYAPI::recurDecrypt($form->_submitValues['TradeInfo'], $form->_paymentProcessor);
          $return_params = CRM_Core_Payment_SPGATEWAYAPI::dataDecode($return_params_decrypt);
          if(!empty($return_params['MerchantOrderNo']) && $saved_params['trxn_id'] == $return_params['MerchantOrderNo']){
            $contrib_params = ['trxn_id' => $return_params['MerchantOrderNo']];
            $contrib_values = $contrib_ids = [];
            CRM_Contribute_BAO_Contribution::getValues($contrib_params, $contrib_values, $contrib_ids);
            CRM_Core_Payment_SPGATEWAYAPI::writeRecord($contrib_values['id'], $return_params);
          }
        }
        // MGP version 1.2
        elseif(!empty($_POST)){
          $contrib_params = ['trxn_id' => $saved_params['trxn_id']];
          $contrib_values = $contrib_ids = [];
          CRM_Contribute_BAO_Contribution::getValues($contrib_params, $contrib_values, $contrib_ids);
          CRM_Core_Payment_SPGATEWAYAPI::writeRecord($contrib_values['id'], $_POST);
        }

        if(!empty($saved_params['trxn_id'])){
          $params['trxn_id'] = $saved_params['trxn_id'];

          // build notify billing info
          $info = civicrm_spgateway_notify_bytrxn($params['trxn_id']);
          if($form_name == 'CRM_Event_Form_Registration_ThankYou'){
            $civicrm_instrument_id = $saved_params[0]['civicrm_instrument_id'];
          }else{
            $civicrm_instrument_id = $saved_params['civicrm_instrument_id'];
          }
          $display = civicrm_spgateway_notify_display($info, $civicrm_instrument_id);
          $isSend = $form->get('invoice_sended', FALSE);
          if(!empty($contrib_values['id']) && !$isSend){
            civicrm_spgateway_notify_generate($contrib_values['id'], TRUE); // send mail
            $form->set('invoice_sended', TRUE);
          }
          $form->assign('payment_instrument', $display); 

          // add result type
          CRM_Contribute_BAO_Contribution_Utils::paymentResultType($form, $params, $status, $msg);
        }
      }
      break;
  }
}

/**
 * Implementation of hook_civicrm_validate()
 */
function civicrm_spgateway_civicrm_validate($form_name, &$form){
  $errors = [];
  if($form_name == 'CRM_Contribute_Form_Contribution_Main'){
    if(!empty($form['payment_processor'])){
      $params = [
        1 => [$form['payment_processor'], 'Integer'],
      ];
      $processor_type = CRM_Core_DAO::singleValueQuery("SELECT payment_processor_type FROM civicrm_payment_processor WHERE id = %1", $params);
      if($processor_type == 'SPGATEWAY'){
        if(!empty($form['installments']) && $form['installments'] > 99){
          $errors['installments'] = t('Installments of recurring must lower than 99.');
        }
        if(!empty($form['installments']) && $form['installments'] > 9 && !empty($form['frequency_unit']) && $form['frequency_unit'] == 'year'){
          $errors['installments'] = t('The years of recurring installments must lower than 9.');
        } 
      }
    }
  }
  return empty( $errors ) ? true : $errors;
}

/**
 * Implementation of hook_civicrm_prepareInvoice()
 */
function civicrm_spgateway_civicrm_prepareInvoice($contribution_id, &$tplParams){
  $sql = "SELECT pp.payment_processor_type FROM civicrm_contribution c
    INNER JOIN civicrm_payment_processor pp ON c.payment_processor_id = pp.id
    WHERE c.id = $contribution_id";
  $payment_process_type = CRM_Core_DAO::singleValueQuery($sql);
  if(preg_match('/SPGATEWAY/', $payment_process_type)){
    $tplParams = civicrm_spgateway_notify_generate($contribution_id, FALSE);
  }
}

function civicrm_spgateway_notify_generate($cid, $send_mail = FALSE){
  civicrm_initialize();
  $info = civicrm_spgateway_notify_info($cid);
  if(!empty($info)){
    $info['display'] = civicrm_spgateway_notify_display($info);
    if($info['#type'] == 'BARCODE'){
      $info['has_receipt'] = 1;
      $info['display'] = civicrm_spgateway_notify_display_barcode($info);
    }

    if($send_mail){
      $message = '';
      CRM_Contribute_BAO_Contribution::getInvoice($cid, $info, $message, $send_mail);
    }
    else{
      return $info;
    }
  }
}

function civicrm_spgateway_notify_bytrxn($trxn_id){
  $cid = CRM_Core_DAO::singleValueQuery("SELECT id FROM civicrm_contribution WHERE trxn_id = %1 OR trxn_id = %2", [
    1 => [$trxn_id, 'String'],
    2 => [$trxn_id.'_1', 'String'],
  ]);
  return civicrm_spgateway_notify_info($cid);
}

function civicrm_spgateway_notify_info($cid){
  civicrm_initialize();
  $dao = CRM_Core_DAO::executeQuery("SELECT s.data FROM civicrm_contribution_spgateway s WHERE s.cid = %1", [1 => [$cid, 'Integer']]);
  $dao->fetch();
  $json = CRM_Core_Payment_SPGATEWAYAPI::dataDecode($dao->data);
  if (is_array($json)) {
    $type = $json['PaymentType'];
  }

  $return = [];
  $invoice_link = CRM_Contribute_BAO_Contribution_Utils::invoiceLink($cid);
  switch($type){
    case 'VACC':
      $return[ts('Bank code')] = $json['BankCode'];
      $return[ts('Virtual account number')] = $json['CodeNo'];
      $return[ts('Payment deadline')] = $json['ExpireDate'].' '.$json['ExpireTime'];
      break;
    case 'CVS':
      $help = '<a href="'.CRM_Utils_System::url('https://www.newebpay.com/website/Page/content/cvs_intro').'" target="_blank">» '.ts('Payment Instructions')."</a>";
      $return[ts('Convenience Store Payment Code')] = $json['CodeNo'];
      $return[ts('Payment deadline')] = $json['ExpireDate'].' '.$json['ExpireTime'];
      $return[] = $help;
      break;
    case 'BARCODE':
      $barcodepath = CRM_Core_Payment_SPGATEWAY::REAL_DOMAIN.'/API/barcode_display/get_barcode_img?barcode_text=';
      $barcode = [$json['Barcode_1'], $json['Barcode_2'], $json['Barcode_3']];
      foreach($barcode as $k => $b){
        $return['#barcode'.$k] = '<div><img src="'.$barcodepath.$b.'" alt="'.$b.'" /></div>';
      }
      $return[ts('Payment slip')] = '<a href="'.$invoice_link.'" target="_blank">» '.ts('Print payment slip').'</a>';
      $return[ts('Payment deadline')] = $json['ExpireDate'].' '.$json['ExpireTime'];
      break;
  }
  if(!empty($return)){
    $return['#type'] = $type;
    $return['#expire'] = $json['ExpireDate'].' '.$json['ExpireTime'];
    $return['#invoice'] = $invoice_link;
    return $return;
  }

  // error fallback
  return [];
}

function civicrm_spgateway_notify_display($info, $payment_instrument_id = NULL){
  $instruments = CRM_Contribute_PseudoConstant::paymentInstrument();
  $output = '';
  foreach($info as $label => $value){
    if(preg_match('/^#/', $label)){
      continue;
    }
    elseif(is_numeric($label)){
      $output .= '<dd>'.' <span>'.$value.'</span></dd>';
    }
    else{
      $output .= '<dd><label>'.$label.':</label>'.' <span>'.$value.'</span></dd>';
    }
  }
  $payment_instrument = !empty($payment_instrument_id) ? '<strong>'.$instruments[$payment_instrument_id].'</strong>' : '';
  $output = $payment_instrument.'<dl>'.$output.'</dl>';
  return $output;
}

function civicrm_spgateway_notify_display_barcode($info){
  $output = '<div style="border:1px solid #000;padding:10px;margin:10px;float:right;width:200px;height:175px;color:#777;">代收店舖章</div>';
  foreach($info as $label => $v){
    if(preg_match('/^#barcode/', $label)){
      $output .= '<div>'.$v.'</div>';
    }
  }
  $output .= '<p><label>'.ts('Payment deadline').':</label> <span>'.$info['#expire'].'</span></p>';
  $output .= '<p><span style="font-size: 9px;">'.ts('Note: Payment confirmation takes 3-4 working days.').'</span></p>';
  return $output;
}


function civicrm_spgateway_cron() {
  $is_maintenance = \Drupal::state()->get('system.maintenance_mode');
  if ($is_maintenance) {
    return;
  }
  $now = time();

  civicrm_initialize();
  // every nights, we check recurring payment result
  // First, check the recur which had received ipn notify today.
  $last = \Drupal::state()->get('civicrm_spgateway_recur_from_ipn_sync', 0);
  if($now - $last > 60000 && date('G') > '17' && date('G') <= '18'){
    $filterDatetime = date('Ymd');
    CRM_Core_Payment_SPGATEWAY::syncTransactionWebLog($filterDatetime);
    \Drupal::state()->set('civicrm_spgateway_recur_from_ipn_sync', $now);
  }

  // Then check all possible recurring to sync.
  $last = \Drupal::state()->get('civicrm_spgateway.recur_sync', 0);
  if($now - $last > 60000 && date('G') > '18' && date('G') < '23'){
    civicrm_spgateway_recur_sync();
    \Drupal::state()->set('civicrm_spgateway.recur_sync', $now);
  }

  // For old neweb.
  /*
  $last = \Drupal::state()->get('civicrm_spgateway.neweb_recur_sync', 0);
  if($now - $last > 60000 && date('G') > '18' && date('G') < '24'){
    $query = "SELECT payment_processor_id FROM civicrm_contribution c INNER JOIN civicrm_payment_processor p ON c.payment_processor_id = p.id WHERE trxn_id LIKE 'r_%' AND payment_processor_type = 'SPGATEWAY' GROUP BY payment_processor_id;";
    $dao = CRM_Core_DAO::executeQuery($query);
    $finishedAll = TRUE;
    while($dao->fetch()) {
      $finished = CRM_Core_Payment_SPGATEWAYNeweb::resync($dao->payment_processor_id);
      if (!$finished) {
        $finishedAll = FALSE;
      }
    }
    if ($finishedAll) {
      \Drupal::state()->set('civicrm_spgateway.neweb_recur_sync', $now);
    }
  }
  */
}

function civicrm_spgateway_recur_sync($days = []){
  civicrm_initialize();
  if(empty($days)){
    $days = [
      date('j'),
      date('j', strtotime('-1 day')),
    ];
    if (date('j') != 1) {
      $days[] = date('j', strtotime('-1 day'));
    }

    // when end of month
		$end_this_month = date('j', strtotime('last day of this month'));
    if (date('j') == $end_this_month) {
      for($i = $end_this_month; $i <= 31; $i++) {
        $days[] = $i;
      }
    }
    $days = array_unique($days);
    CRM_Core_Error::debug_var('spgateway_recur_sync_days', $days);
  }

  // Query for the recurring need to do checking.
  $query = "SELECT (SELECT count(c.id) FROM civicrm_contribution c WHERE c.contribution_recur_id = r.id AND c.receive_date >= %2 AND c.receive_date <= %3 ) AS contribution_count, r.*
  FROM civicrm_contribution_recur r
  INNER JOIN civicrm_payment_processor pp ON r.processor_id = pp.id
  WHERE r.contribution_status_id = 5 AND r.frequency_unit = 'month' AND (DAY(r.start_date) = %1 OR r.cycle_day = %1)
  AND pp.payment_processor_type = 'SPGATEWAY'
  AND (pp.url_api IS NULL OR pp.url_api = '' OR pp.url_api = '0')
  AND (SELECT count(c.id) FROM civicrm_contribution c WHERE c.contribution_recur_id = r.id AND c.receive_date >= %2 AND c.receive_date <= %3 ) = 0
  AND COALESCE((SELECT MAX(co.created_date) FROM civicrm_contribution co WHERE co.contribution_recur_id = r.id), CURDATE()) >= DATE_SUB(CURDATE(), INTERVAL 3 MONTH)
  ORDER BY r.create_date ASC";
  foreach($days as $d){
    $d = (string) $d;
    CRM_Core_Error::debug_log_message('civicrm_spgateway: Start to sync recurring for day '.$d);
    if ($d >= 29) {
      $d = (string) $d;
      $query_params = [
        1 => [$d, 'String'],
        2 => [date('Y-m-28').' 00:00:00', 'String'],
        3 => [date('Y-m-').sprintf('%02s', $d).' 23:59:59', 'String'],
      ];
    }
    else {
      $d = (string) $d;
      $query_params = [
        1 => [$d, 'String'],
        2 => [date('Y-m-').sprintf('%02s', $d).' 00:00:00', 'String'],
        3 => [date('Y-m-').sprintf('%02s', $d).' 23:59:59', 'String'],
      ];
    }
    CRM_Core_Error::debug_var('spgateway_recur_sync_query_params', $query_params);
    $result = CRM_Core_DAO::executeQuery($query, $query_params);

    while($result->fetch()){
      CRM_Core_Error::debug_log_message("civicrm_spgateway: count: {$result->contribution_count}, recur_id: {$result->id}, recur start_date: {$result->start_date}, recur cycle_day: {$result->cycle_day};");
      CRM_Core_Error::debug_log_message("civicrm_spgateway: Executing check for recur_id: {$result->id};");
      // check if is next day of expect recurring
      CRM_Core_Payment_SPGATEWAY::recurSync($result->id);
      usleep(300000); // sleep 0.3 second
      CRM_Core_Error::debug_log_message("civicrm_spgateway: Finished checking recur_id: {$result->id};");
    }
    $result->free();
    $result = NULL;
    CRM_Core_Error::debug_log_message("civicrm_spgateway: Finished all spgateway recurring executed for day: {$d}");
  }
}

function civicrm_spgateway_civicrm_enableDisable($recordBAO, $recordID, $isActive) {
  if ($recordBAO == 'CRM_Contribute_BAO_ContributionRecur' && empty($isActive)) {
    $payment_processor_id = CRM_Core_DAO::getFieldValue('CRM_Contribute_DAO_ContributionRecur', $recordID, 'processor_id');
    if (empty($payment_processor_id)) {
      $payment_processor_id = CRM_Core_DAO::getFieldValue('CRM_Contribute_DAO_Contribution', $recordID, 'payment_processor_id', 'contribution_recur_id');
    }
    if (CRM_Core_DAO::getFieldValue('CRM_Core_DAO_PaymentProcessor', $payment_processor_id, 'payment_processor_type') == 'SPGATEWAY') {
      CRM_Core_DAO::setFieldValue('CRM_Contribute_DAO_ContributionRecur', $recordID, 'contribution_status_id', 3);
    }
  }
}

function civicrm_spgateway_mobile_checkout($type, $post, $objects){
  $return = CRM_Core_Payment_SPGATEWAY::mobileCheckout($type, $post, $objects);
  return $return;
}


function _civicrm_spgateway_cancel_recuring_message(){
  $js = '<h3>
藍新金流提醒
</h3>
<p>
  藍新請透過以下步驟，先至金流後台改狀態，再到此完成取消定捐。
</p>
<p>
  <ol>
    <li>先登入到<a target="_blank" href="https://www.newebpay.com/main/login_center/single_login">藍新的後台</a>，找到該筆定期定額進行取消操作</li>
    <li>藍新後台確認取消後，再到 CRM 後台取消（就是此功能）。</li>
  </ol>
</p>
<p>
  <span style="color:#ff0000;">注意</span>：若沒有在藍新後台取消，則該筆定捐<span style="color:#ff0000;">不會</span>停止喔！按下「確定」前請確認<b>您已在藍新後台取消該筆定捐</b>。
</p>
<p>
  詳情請參考<a target="_blank" href="https://neticrm.tw/resources/2497#p1"> netiCRM 手冊說明</a>
</p>';
  return $js;
}


function _civicrm_spgateway_error_msg($code){
  $code = (string) $code;
  // success
  if($code == '1' || $code == '2'){
    return;
  }

  // error
  $msg = [
    'PER10001' => '商店資料取得失敗',
    'PER10002' => '資料解密錯誤',
    'PER10003' => 'POST 資料傳遞錯誤',
    'PER10004' => '資料不齊全',
    'PER10005' => '資料不可空白',
    'PER10006' => '商品名稱不得含有 JavaScript 語法、CSS 語法',
    'PER10007' => '委託金額格式不對,金額必須為數字',
    'PER10008' => '委託金額不能為零',
    'PER10009' => '週期設定錯誤! (W=週,M=月,Y=年)',
    'PER10010' => '商店訂單編號錯誤,只允許英數與底線',
    'PER10011' => '商店訂單編號長度限制為 20 字',
    'PER10012' => '回傳格式格式錯誤,只接受 JSON 或 String',
    'PER10013' => '週期授權時間資料不正確,日期格式為 1 到 7',
    'PER10014' => '週期授權時間資料不正確,日期格式為 1 到 7(長度不符)',
    'PER10015' => '定期授權時間資料不正確,日期格式為 01 到 31',
    'PER10016' => '定期授權時間資料不正確,日期格式為 01 到 31(長度不符)',
    'PER10017' => '定期授權時間資料不正確,日期格式為 01 到 31',
    'PER10018' => '定期授權時間資料不正確,日期格式為 01 到 31',
    'PER10019' => '定期授權時間資料不正確,長度不符',
    'PER10020' => '首期授權模式設定錯誤(1-3),請檢查',
    'PER10021' => '備註說明不得含有 JavaScript 語法、CSS 語法',
    'PER10022' => '授權期數格式不對,必須為數字',
    'PER10023' => '授權期數不能為零',
    'PER10024' => '授權期數不能多於 999 次',
    'PER10025' => '返回商店網址格式錯誤',
    'PER10026' => '每期授權通知網址格式錯誤',
    'PER10027' => '是否開啟付款人資訊設定錯誤',
    'PER10028' => '付款人電子信箱格式錯誤',
    'PER10029' => '商店代號停用',
    'PER10030' => '商店信用卡資格停用',
    'PER10031' => '商店定期定額資格停用',
    'PER10032' => '該訂單編號已重覆',
    'PER10033' => '寫入委託單失敗',
    'PER10034' => '授權失敗,委託單建立失敗',
    'PER10035' => '委託單更新授權結果失敗',
    'PER10036' => '驗證資料錯誤(來源不合法)',
    'PER10037' => '付款頁參數不足',
    'TRA10001' => '商店代號錯誤',
    'TRA10003' => '金額格式錯誤',
    'TRA10008' => '資料加密錯誤',
    'TRA10010' => '商店代號空白',
    'TRA10012' => '商店代號停用',
    'TRA10013' => '信用卡資格停用',
    'TRA10014' => '信用卡授權失敗',
    'TRA10037' => '商家自訂單筆錯誤，只允許英數與底線',
    'TRA10041' => '網址格式錯誤',
    'TRA10042' => '信用卡卡號格式錯誤',
    'TRA10043' => '信用卡到期年月格式錯誤',
    'TRA10044' => '卡號未四碼格式錯誤',
    'TRA10052' => '商店不允許國外卡交易',
    'TRA10053' => '此商店目前無法使用信用卡交易',
    'TRA10054' => '檢查碼錯誤',
    'TRA10061' => '特約商店信用卡收單行設定錯誤',
    'TRA10061_g' => '信用卡收單行設定錯誤',
    'TRA10075' => '新增交易明細失敗',
    'TRA10076' => '查無此 Token',
    'TRA10078' => '信用卡背面末三碼檢查錯誤',
    'TRA10079' => '卡片到期日檢查錯誤',
    'TRA10080' => 'Token綁定的Term對應失敗',
    'TRA10094' => '資料取消失敗',
    'TRA10095' => '此筆交易已過關帳時間，不可取消',
    'TRA10096' => 'Token 標記有效年月-數字格式錯誤',
    'TRA10097' => 'Token 標記有效年月-月份格式錯誤',
    'TRA10098' => 'Token 標記有效年月-設定錯誤(已過期)',
    'TRA10100' => 'Token 付款人綁定資料不可空白',
    'TRA10100C' => '中信分期系統維護中',
    'TRA10100E' => '玉山系統維護中',
    'TRA10100T' => '台新系統維護中',
    'TRA10101'  => '使用 Token 交易無法提供分期付款',
    'TRA10681'  => '信用卡交易序號編號錯誤',
    'TRA20001' => '交易資料新增失敗，金融機構取消授權批次處理中（需由金融機構批次處理）',
    'TRA20010' => '無此刷卡付款方式',
    'TRA20011' => '此商店不支援此信用卡交易',
    'TRA10678' => '銀聯卡退款失敗',
    'TRA10675' => '紅利交易只接受全額請退款',
    'TRA10702' => '達到執行請退款筆數上限，暫時無法使用本功能，請待 1 小時後解鎖；送出後檢查交易失敗，頁面超過 180 秒',
    'TRA11002' => '失敗過多導致暫停使用本功能，請待 4 小時解鎖',
    'TRA20002' => '查無交易資料',
    'TRA20004' => '商店訂單編號重覆',
    'TRA20027' => '此訂單已申請過退款，退款中',
    'TRA20028' => '可退款金額不足，請查看常見問題 https://www.newebpay.com/website/Page/content/faq',
    'TRA40014' => 'TimeStamp 欄位錯誤',
    'MPG01002' => '時間戳記不可空白',
    'MPG01005' => 'TokenTerm 不可空白/設定錯誤',
    'MPG01008' => '分期參數設定錯誤',
    'MPG01009' => '商店代號不可空白',
    'MPG01010' => '程式版本設定錯誤',
    'MPG01011' => '回傳規格設定錯誤',
    'MPG01012' => '商店訂單編號不可空白/設定錯誤',
    'MPG01013' => '付款人電子信箱設定錯誤',
    'MPG01014' => '網址設定錯誤',
    'MPG01015' => '訂單金額不可空白/設定錯誤；此筆交易超過商店單筆金額限制，請與商店連繫',
    'MPG01016' => '檢查碼不可空白',
    'MPG01017' => '商品資訊不可空白',
    'MPG01018' => '繳費有效期限設定錯誤',
    'MPG01023' => '交易加密資料不可空白',
    'MPG01024' => '交易加密 SHA 資料不可空白',
    'MPG01025' => '金融機構格式錯誤：僅接受大小寫英文與半形逗號，參數大小寫有區分，請依文件規格帶入',
    'MPG01026' => '金融機構格式錯誤，不接受指定參數；帶入的銀行有誤，請勿帶入不支援之銀行',
    'MPG01027' => '一銀維護中，請選擇其他金融機構；該時段為第一銀行的維護時間，請指定其他銀行',
    'MPG01028' => '訂單細項格式錯誤',
    'MPG01029' => '訂單金額與訂單細項總金額不相符',
    'MPG01030' => '訂單細項品項編號不可重複',
    'MPG02001' => '檢查碼錯誤',
    'MPG02002' => '查無商店開啟任何金流服務',
    'MPG02003' => '支付方式未啟用，請洽客服中心',
    'MPG02004' => '匯率時間戳記不存在，請確認',
    'MPG02005' => '驗證資料錯誤（來源不合法）',
    'MPG02006' => '信用卡收單機構系統發生異常，請洽客服中心',
    'MPG02007' => '本商店強制指定需檢核轉出行，請先啟用智慧 ATM2.0 服務',
    'MPG02008' => 'SourceType 參數錯誤（本商店強制指定需檢核轉出行）',
    'MPG02009' => '不可修改銀行代號與帳號時，須提供指定轉帳的銀行代號與帳號',
    'MPG02010' => '此版本不支援，請升級至 v2.3',
    'MPG03001' => 'FormPost 加密失敗',
    'MPG03002' => '拒絕交易 IP',
    'MPG03003' => 'IP 交易次數限制：N 分鐘內不可交易達 M 次',
    'MPG03004' => '商店狀態已被暫停或關閉，無法進行交易',
    'MPG03005' => '回傳參數資料不存在或解密失敗',
    'MPG03006' => '回傳參數資料不存在或解密失敗',
    'MPG03007' => '該筆訂單交易資訊不存在，請重新交易；（物流服務）查無此商店代號',
    'MPG03008' => '已存在相同的商店訂單編號',
    'MPG03009' => '交易失敗；SHA-256 檢查不符合',
    'MPG03010' => '驗證資料不存在或錯誤（玉山 Wallet、台灣 Pay、BitoPay 錯誤代碼）',
    'MPG03011' => '訂單資料已不存在，請重新交易（玉山 Wallet、台灣 Pay、BitoPay 錯誤代碼）',

    'MPG05001' => '未有信用卡驗證資料或信用卡驗證資料解密失敗',
    'MPG05002' => '信用卡卡號長度不足；未有商店代號；本商店不支援此信用卡付款，請改用其他發卡行之信用卡',
    'MPG05003' => '此卡不支援一次付清/分期付款/紅利付款，請改用相容之信用卡或其他支付方式',
    'MPG05004' => '發卡行暫時無法提供信用卡分期付款服務',
    'MPG05005' => '警示交易',
    'MPG05006' => '物流設定參數 [LgsType] 錯誤（限輸入 C2C 或 B2C）',
    'MPG05007' => '請開啟其他支付方式，才能使用超商取貨不付款服務',
    'MPG05008' => '因金額限制無法使用物流服務（訂單金額需小於 20,000 元）',
    'MPG05009' => '超商取貨服務未啟用（服務型態），請洽客服中心。服務型態：取貨付款、取貨不付款',
    'ACC10005' => '會員已被暫時停權或永久停權，請洽藍新金流客服中心查詢',
    'MEM40008' => '必填欄位資料不可空白',
    'MEM40012' => '必填欄位資料傳遞錯誤',
    'MEM40013' => '必填欄位資料不齊全',
    'MEM40014' => '傳送時間錯誤',
    'NOR1001' => '連線異常',
    '1101' => '退款失敗',
    '1102' => '查無商店',
    '1103' => '查無訂單資料',
    '1104' => '訂單狀態不為可退款狀態',
    '1105' => '可退金額不足',
    '1106' => '錢包類型不符',
    '1107' => '尚未請款',
    '1108' => '僅支援全額退款',
    '1109' => '退款交易申請中，請稍後',
    '1110' => '商店支付方式未啟用',
    '1111' => '查詢商店閘道設定，查無資料',
    '1116' => '可退款金額不足，請查看常見問題 https://www.newebpay.com/website/Page/content/faq',
    '2100' => '最低金額為 1',
    '4101' => 'EncryptData_ 不可為空白',
    '4102' => 'HashData_ 不可為空白',
    '4103' => 'HashData_ 資料檢查不符合',
    '4104' => '加密資料有誤，請確認 Hash_Key 與 Hash_IV 是否正確',
    '4105' => 'TimeStamp 為空',
    '4106' => 'UID_ 不可為空白',
    '9000' => '網路連線失敗',
    'uncertain' => 'Go check in www.newebpay.com',
  ];
  if(!empty($msg[$code])){
    // return t($msg[$code]);
    return $msg[$code];
  }
  else{
    return t('Error when processing your payment.');
  }
}
