<?php
/**
 * Implementation of hook_form_alter
 *
 * Support webform_civicrm address
 */
function civicrm_twaddress_form_alter(&$form, $form_state, $form_id){
  static $add;
  $override = array();
  if (substr($form['#id'], 0, 20) == 'webform-client-form-') {
    // for now we only support field below 2 fieldset
    foreach($form['submitted'] as $k => $c){
      if(!is_array($c)) continue;
      $children = element_children($c);
      if(count($children)){
        foreach($children as $name){
          $cchildren = element_children($form['submitted'][$k][$name]);
          if(count($cchildren)){
            foreach($cchildren as $nname){
              _civicrm_twaddress_is_addr_field($nname, $form['submitted'][$k][$name][$nname], $override);
            }
          }
          _civicrm_twaddress_is_addr_field($name, $form['submitted'][$k][$name], $override);
        }
      }
      _civicrm_twaddress_is_addr_field($name, $form['submitted'][$k][$key], $override);
    }
    if(count($override)>=3){
      // check post value
      if(!empty($form_state['post'])){
        foreach($override as $k => $v){
          foreach($v as $kk => $vv){
            $override[$k][$kk]['default'] = _civicrm_twaddress_search_value($vv['key'], $form_state['post']);
          }
        }
      }

      if(!$add){
        $path = drupal_get_path("module",'civicrm_twaddress');
        drupal_add_js($path."/twzipcode.js");
        $add = 1;
      }
      _civicrm_twaddress_webform_js($override, $add_js = TRUE);
    }
  }
}

function _civicrm_twaddress_is_addr_field($name, &$obj, &$override){
  if(strstr($name, 'postal_code') && !strstr($name,'postal_code_suffix')){
    $key = _civicrm_twaddress_webform_key($name);
    $override['zipName'][$key]['key'] = $name;
    $override['zipName'][$key]['default'] = '';
  }
  elseif(strstr($name, 'state_province')){
    $key = _civicrm_twaddress_webform_key($name);
    $override['countyName'][$key]['key'] = $name;
    foreach($e->_options as $v){
      if($v['attr']['value']){
        $county_options[$v['attr']['value']] = $v['text'];
      }
    }
    // $default = $default ? $default : $_POST[$name];
    $override['countyName'][$key]['default'] = '';
  }
  elseif(strstr($name, 'city')){
    $key = _civicrm_twaddress_webform_key($name);
    // hide field

    // $default = $default ? $default : $_POST[$name];
    $override['areaName'][$key]['key'] = '_'.$name;
    $override['areaName'][$key]['name'] = $name;
    // $override['areaName'][$key]['default'] = $default;
  }
  return $override;
}


/**
 * Implementation of hook_civicrm_buildForm().
 */
function civicrm_twaddress_civicrm_buildForm($formName, &$form) {
  static $add;
  // whatever, reorder. 
  foreach ($form->_elements as $k => $e) {
    $name = $e->_attributes['name'];
    if(strstr($name, 'state_province') || !empty($e->_attributes['state-province'])){
      $element = $form->getElement($name);
      $options = civicrm_twaddress_extract($element->_options);

      $optgrp = FALSE;
      foreach ($element->_options as $o => $opt) {
        if (!empty($opt['options'])) {
          // reorder sub dir
          $optgrp = TRUE;
          $neworder = _civicrm_twaddress_reorder($opt['options']);
          $element->_options[$o]['options'] = $neworder;
        }
      }
      if (!$optgrp) {
        $neworder = _civicrm_twaddress_reorder($element->_options);
        $element->_options = $neworder;
      }
    }
  }

  // we don't support outside of civicrm yet
  /*
  if(arg(0) != 'civicrm'){
    return;
  }
  */
  
  // we don't support ajax form
  $deny = array();
  if(in_array($formName,$deny)){
    return;
  }
  
  // we don't process report form
  if(strpos($formName, 'Report_Form')){
    return;
  }
  // we don't change form on step 2 / 3 / 4
  if(strpos($formName, 'Confirm') || strpos($formName, 'ThankYou')){
      $js = 'jQuery(function($){
var arrChecked = [];
$(".custom_pre-group fieldset").children().each(checkForm);
$(".custom_post-group fieldset").children().each(checkForm);

function checkForm(){
    var c = $(this).attr("class");
    if (typeof c !== "string") {
      return;
    }
    for (var i = 0; i < arrChecked.length; i++) {
      if (typeof arrChecked[i] === "string" && typeof c === "string") {
        var re = new RegExp(arrChecked[i], "g");
        if(c.match(re)) {
          return;
        }
      }
    }
    // arrType = [];
    arrFieldType = ["state_province-","postal_code-","city-"];
    match = c.match(/(state_province-|postal_code-|city-)([^ ]+)-section/);
    if(match && match.length >=3){
      type = match[2];
      classname = match[0];
      arrChecked.push(classname);
      $current = $(this).next();
      arrItems = [];
      while($current.next().length!==0){
        match = $current.attr("class").match(RegExp("(state_province-|postal_code-|city-)" + type + "-section"));
        if(match && match.length>=2){
          arrItems.push($current);
        }
        $current = $current.next();
      }
      if(arrItems.length>=2){
        for (var i = 0; i < arrItems.length; i++) {
          arrChecked.push(arrItems[i].attr("class").match(/(state_province-|postal_code-|city-)([^ ]+)-section/)[0]);
          $(this).find(".content").append(arrItems[i].find(".content").text());
          arrItems[i].hide();
        }
      }
    }
  }
            
        });';
      drupal_add_js($js , 'inline');
    return;
  }
  //
  $enable = TRUE;
  $form_name = $form->_attributes['name'];
  if($form_name == 'Dynamic'){
    $is_dynamic = true;
    if(is_numeric(strpos($_GET['q'], 'user/register'))){
      $form_name = 'user-register-form';
    }else{
      $form_name = 'user-profile-form';
    }
  }
  foreach ($form->_elements as $k => $e) {
    $name = $e->_attributes['name'];
    if(strstr($name, 'postal_code') && !strstr($name,'postal_code_suffix')){
      $key = _civicrm_twaddress_key($name);
      $default = isset($form->getElement($name)->_attributes['value']) ? $form->getElement($name)->_attributes['value'] : NULL;
      $override['zipName'][$key]['key'] = $name;
      $override['zipName'][$key]['default'] = $default ? $default : $form->getElement($name)->_findValue($form->_defaultValues);
    }
    if(strstr($name, 'state_province')){
      $key = _civicrm_twaddress_key($name);
      $override['countyName'][$key]['key'] = $name;
      foreach($e->_options as $v){
        if($v['attr']['value']){
          $county_options[$v['attr']['value']] = $v['text'];
        }
      }
      $default = isset($form->getElement($name)->_values[0]) ? $form->getElement($name)->_values[0] : NULL; 
      $default = $default ? $default : $form->getElement($name)->_findValue($form->_defaultValues);
      $default = $default ? $default : (isset($form->_submitValues[$name]) ? $form->_submitValues[$name] : NULL);
      // Find that default value is depands on zip code. The code here is no use.
      $override['countyName'][$key]['default'] = isset($county_options[$default]) ? $county_options[$default] : $default;
    }
    if(strstr($name, 'city')){
      $key = _civicrm_twaddress_key($name);
      // hide field

      $default = isset($form->getElement($name)->_attributes['value']) ? $form->getElement($name)->_attributes['value'] : NULL; 
      $default = $default ? $default : $form->getElement($name)->_findValue($form->_defaultValues);
      $default = $default ? $default : (isset($form->_submitValues[$name]) ? $form->_submitValues[$name] : NULL);
      // Find that default value is depands on zip code. The code here is no use.
      $override['areaName'][$key]['key'] = '_'.$name;
      $override['areaName'][$key]['name'] = $name;
      $override['areaName'][$key]['default'] = $default;
    }
    if(strstr($name, 'country')){
      $key = _civicrm_twaddress_key($name);

      $default = isset($form->getElement($name)->_attributes['value']) ? $form->getElement($name)->_attributes['value'] : NULL; 
      $default = $default ? $default : $form->getElement($name)->_findValue($form->_defaultValues);
      $default = $default ? $default : (isset($form->_submitValues[$name]) ? $form->_submitValues[$name] : NULL);
      // Find that default value is depands on zip code. The code here is no use.
      $override['country'][$key]['key'] = '_'.$name;
      $override['country'][$key]['name'] = $name;
      $override['country'][$key]['default'] = $default;
    }
  }

  if(count($override)>=3 && $enable){
    if(!$add){
      $path = drupal_get_path("module",'civicrm_twaddress');
      drupal_add_js($path."/twzipcode.js");
      $add = 1;
    }

    if(arg(1) == 'contribute' || arg(1) == 'event' || $is_dynamic){
      _civicrm_twaddress_grouping_js();
    }

    if(!empty($_GET['snippet']) && $_GET['block'] == 'Address'){
      reset($form->_fields);
      $js = _civicrm_twaddress_common_js($override, $form_name, FALSE);
      $js = implode("\n", $js);
      $js = '<script type="text/javascript">'.$js.'</script>';
      print($js);
    }
    else{
      _civicrm_twaddress_common_js($override, $form_name, $add_js = TRUE);
    }
  }
}

function civicrm_twaddress_extract(&$options){
  foreach($options as &$o){
    $return[$o['text']] = $o;
  }
  return $return;
}

function civicrm_twaddress_order(){
  return
  array(
    '', // for order 0
    '基隆市',
    '臺北市',
    '新北市',
    '桃園市',
    '新竹市',
    '新竹縣',
    '苗栗縣',
    '臺中市',
    '彰化縣',
    '南投縣',
    '嘉義市',
    '嘉義縣',
    '雲林縣',
    '臺南市',
    '高雄市',
    '屏東縣',
    '臺東縣',
    '花蓮縣',
    '宜蘭縣',
    '澎湖縣',
    '金門縣',
    '連江縣',
    '南海諸島',
  );
}

function _civicrm_twaddress_key($name){
  if(preg_match('/Primary/', $name)){
    return 'Primary';
  }
  preg_match('/\d/', $name, $matches);
  $key = is_numeric($matches[0]) ? $matches[0] : 1;

  return $key;
}

function _civicrm_twaddress_webform_key($name){
  list($key) = explode('_address', $name);
  return $key;
}

function _civicrm_twaddress_grouping_js(){
  $js = '
    jQuery(function($){
      // find a address group to collapsed to single line
      var ids = {};
      var addr_fields = $(".crm-section").filter(function(){
        var classes = $(this).attr("class").split(" ");
        for (var i=0; i<classes.length; i++) {
          if(classes[i].slice(0,7) == "editrow"){
            // for user/register page and profile edit page
            classes[i] = classes[i].substr(8);
            $(this).addClass(classes[i]);
          }
          if (classes[i].slice(0,14) == "state_province" || classes[i].slice(0, 4) == "city" || classes[i].slice(0, 11) == "postal_code") {
            var matches = classes[i].match(/\d+|Primary/);
            var rel = "g"+matches[0];
            $(this).attr("rel", rel);
            if(typeof(ids[rel]) == "undefined"){
              ids[rel] = 1;
            }
            else{
              ids[rel] = ids[rel]+1;
            }
            return true;
          }
        }
      });

      for(property in ids) {  
        if(ids[property] == 3){
          var id = property.replace("g", "");
          // this the right group
          $("[rel=\'"+property+"\']").each(function(){
            var classes = $(this).attr("class");
            if(!classes.match(/state_province/g)){
              var html = $(this).find(".content>*").appendTo(".state_province-"+id+"-section .content");
              $(this).hide();
            }
          });
        }
      }
    });
  ';
  drupal_add_js($js , 'inline');
}

function _civicrm_twaddress_common_js($field, $form_name, $add_js = TRUE){
  $return = array();
  $count = 0;
  foreach($field['areaName'] as $k => $v){
    $random_id = mt_rand(1000, 9999);
    $count++;
    $select_id = "twaddr-area-{$k}-{$random_id}";
    $insert = "<div class='crm-form-elem crm-form-select md-elem md-select md-select-single'><select id='{$select_id}' name='{$field['areaName'][$k]['key']}' class='form-select'></select></div>";

    $js = '
    jQuery(function($){
      if( $("form#'.$form_name.' input[name=\''.$field['areaName'][$k]['name'].'\']").length ){
        ';
    $address_info_json = '{
      zipField:"'.$field['zipName'][$k]['name'].'",
      countyField:"'.$field['countyName'][$k]['name'].'",
      areaField:"'.$field['areaName'][$k]['name'].'",
      zipName:"'.$field['zipName'][$k]['key'].'",
      countyName:"'.$field['countyName'][$k]['key'].'",
      areaName:"'.$field['areaName'][$k]['key'].'",
      zipSel:"'.$field['zipName'][$k]['default'].'",
      countySel:"'.$field['countyName'][$k]['default'].'",
      areaSel:"'.$field['areaName'][$k]['default'].'"
    }';

    if( !empty($field['country'][$k])){
      $js .= '
      if( $("form#'.$form_name.' select[name=\''.$field['country'][$k]['name'].'\']").length ){
            $("select[name=\''.$field['country'][$k]['name'].'\']").change(function(){
              if($(this).val() == "1208"){
                applyTWZIPAddress("'.$select_id.'",'.$address_info_json.');
              }else{
                cancelTWZIPAddress("'.$select_id.'",'.$address_info_json.');
              }
            }).trigger("change");
            var countryID       = "#'.$field['country'][$k]['name'].'"
            var stateProvinceID = "#'.$field['countyName'][$k]['key'].'"
            var callbackURL     = "/civicrm/ajax/jqState"
            cj(countryID).chainSelect(stateProvinceID, callbackURL, {defaultValue:"'._civicrm_twaddress_get_province_id($field['countyName'][$k]['default']).'"} );
          }
      ';
    }elseif(!($_GET['q']=='civicrm/contact/add' && $k > 1)){
      // In contact edit page, the addresses after second
      // will auto use ajaxComplete to build blockes.
      $js .= 'applyTWZIPAddress("'.$select_id.'",'.$address_info_json.');';
    }


    $js .= '
        cj(document).ajaxComplete(function(event, xhr, settings){
          var url = settings.url;
          if(url.match("/civicrm/ajax/jqState")){
            var reg_country_no = /_id=country-' .$k. '/;
            if(url.match("'.$field['country'][$k]['name'].'") && url.match("_value=1208")){
              $("#'.$field['countyName'][$k]['key'].'").val('._civicrm_twaddress_get_province_id($field['countyName'][$k]['default']).');
            }else if(reg_country_no.test(url)){

              $("#'.$field['areaName'][$k]['name'].'").val("");
              $("#'.$field['zipName'][$k]['key'].'").val("");
            }
          }
        });
      }
    });

    ';
    if($add_js){
      drupal_add_js($js , 'inline');
    }
    else{
      $return[$k] = $js;
    }
  }
  $js = '
    (function($){
      applyTWZIPAddress = function(select_id, address_info){
        var $form = $("form#'.$form_name.'");
        $("[for=\'"+address_info.areaField+"\'].error").remove();
        $("[for=\'"+address_info.countyName+"\'].error").remove();
        $("[for=\'"+address_info.zipName+"\'].error").remove();
        if(!$("#"+select_id).length){
          var select = "<div class=\'crm-form-elem crm-form-select md-elem md-select md-select-single\'><select id=\'"+select_id+"\' name=\'" + address_info.areaName + "\' class=\'form-select\'></select></div>";
          $(select).insertAfter($("form#'.$form_name.' input[name=\'" + address_info.areaField + "\']").parent());
        }else if(!$("#"+select_id).is(":visible")){
          $("#"+select_id).parent().show();
        }
        $("input[name=\'" + address_info.areaField + "\']").parent().hide();
        $("select[name=\'" + address_info.areaName + "\']").change(function(){
          var v = $(this).val();
          $("input[name=\'" + address_info.areaField + "\']").val(v);
        });
        $("input[name=\'" + address_info.zipName + "\']").addClass("readonly post-code").wrap("<div class=\'crm-form-elem crm-form-textfield md-elem md-textfield crm-form-readonly crm-form-post-code\'></div>");

        $form.twzipcode(address_info);
      }

      cancelTWZIPAddress = function(select_id, address_info){

        var $form = $("form#'.$form_name.'");
        $("input[name=\'" + address_info.areaField + "\']").parent().show();
        $("select[name=\'" + address_info.areaName + "\']").parent().hide();
        $("input[name=\'" + address_info.zipName + "\']").removeClass("readonly post-code").removeAttr("readonly").unwrap();

      }

      cj(document).ajaxComplete(function(event, xhr, settings){
          var url = settings.url;
          if(url.match("/civicrm/contact/add") && url.match("block=Address")){
            var $res = $(xhr.responseText);
            var nth_address = $res.filter(".crm-edit-address-block").attr("id").match(/\d+/)[0];
            var field_id = "twaddr-area-"+nth_address;
            var countySel_id = $res.find("#address_"+nth_address+"_state_province_id").val();
            var countySel = $res.find("#address_"+nth_address+"_state_province_id option:selected").text();
            var zipSel = $res.find("#address_"+nth_address+"_postal_code").val();
            var areaSel = $res.find("#address_"+nth_address+"_city").val();

            applyTWZIPAddress("twaddr-area-"+nth_address,{
              zipField:"",
              countyField:"",
              areaField:"address["+nth_address+"][city]",
              zipName:"address["+nth_address+"][postal_code]",
              countyName:"address["+nth_address+"][state_province_id]",
              areaName:"_address["+nth_address+"][city]",
              zipSel:zipSel,
              countySel:countySel,
              areaSel:areaSel
            });
          }
        });
      })(jQuery);
  ';

  if($add_js){
    drupal_add_js($js , 'inline');
  }
  else{
    $return[] = $js;
  }
  $return = array_reverse($return);
  return $return;
}

function _civicrm_twaddress_webform_js($field, $form_name, $add_js = TRUE){
  $return = array();
  foreach($field['areaName'] as $k => $v){
    $count++;
    $insert = "<select name='{$field['areaName'][$k]['key']}' class='form-select'></select>";

    $js = '
    jQuery(function($){
      if( $("input[name*=\''.$field['areaName'][$k]['name'].'\']").length ){
        $("'.$insert.'").insertAfter("input[name*=\''.$field['areaName'][$k]['name'].'\']");
        $("input[name*=\''.$field['areaName'][$k]['name'].'\']").hide();
        $("select[name*=\''.$field['areaName'][$k]['key'].'\']").change(function(){
          var v = $(this).val();
          $("input[name*=\''.$field['areaName'][$k]['name'].'\']").val(v);
        });
        $("input[name*=\''.$field['zipName'][$k]['key'].'\']").addClass("readonly post-code");
        var zipname = $("input[name*=\''.$field['zipName'][$k]['key'].'\']").attr("name");
        var areaname = $("select[name*=\''.$field['areaName'][$k]['key'].'\']").attr("name");
        var countyname = $("select[name*=\''.$field['countyName'][$k]['key'].'\']").attr("name");

        $("form[name=\''.$form_name.'\']").twzipcode({
          zipName:zipname,
          countyName:countyname,
          areaName:areaname,
          zipSel:"'.$field['zipName'][$k]['default'].'",
          countySel:"'.$field['countyName'][$k]['default'].'",
          areaSel:"'.$field['areaName'][$k]['default'].'"
        });
      }
    });
    ';
    if($add_js){
      drupal_add_js($js , 'inline');
    }
    else{
      $return[$k] = $js;
    }
  }
  return $return;
}

function _civicrm_twaddress_search_value($key, $array){
  if(!isset($array[$key])){
    foreach($array as $k => $v){
      if(is_array($v)){
        $return = _civicrm_twaddress_search_value($key, $v);
        if($return){
          break;
        }
      }
    }
  }
  else{
    return $array[$key];
  }
  return $return;
}

function _civicrm_twaddress_get_province_id($name){
  $arr = array( "南投縣"=> "4855",
    "臺中市"=> "5219",
    "臺北市"=> "5221",
    "臺南市"=> "5224",
    "臺東縣"=> "4861",
    "嘉義市"=> "5222",
    "嘉義縣"=> "4849",
    "基隆市"=> "4864",
    "宜蘭縣"=> "4852",
    "屏東縣"=> "4857",
    "彰化縣"=> "4848",
    "新北市"=> "4860",
    "新竹市"=> "5223",
    "新竹縣"=> "4850",
    "桃園市"=> "4862",
    "澎湖縣"=> "4856",
    "花蓮縣"=> "4851",
    "苗栗縣"=> "4854",
    "連江縣"=> "5225",
    "金門縣"=> "5226",
    "雲林縣"=> "4863",
    "高雄市"=> "5220",
  );
  return $arr[$name];
}

function _civicrm_twaddress_reorder($options) {
  $order = civicrm_twaddress_order();
  $neworder = array();

  foreach($order as $k => $v){
    // if option is '-- select --', skip to next.
    if(empty($options[$v]['attr']['value'])) continue;
    if(!empty($options[$v])){
      $opt = $options[$v];
      $neworder[$v] = $opt;
    }
  }
  if (empty($neworder)) {
    return $options;
  }
  else {
    return $neworder;
  }
}
